<?php $this->partial('shared/header'); ?>

        <?php $this->partial('shared/warningBrowser'); ?>
        
        <?php $this->partial('shared/menus'); ?>

        <header class="title privacy">
            <aside class="shadow">
                <div>
                    <h1>Privacy Policy</h1>
                </div>
            </aside>
        </header>

        <section class="privacy font OpenSans regular">
                <aside class="shadow">
                    <section>

                    <p>This Privacy Policy governs the manner in which XZERO collects, uses, maintains and discloses information collected from users (each, a "User") of the <a href="http://xzero.io">http://xzero.io</a> website ("Site"). This privacy policy applies to the Site and all products and services offered by XZERO.</p>
                    
                    <h4>Personal identification information</h4>
                    
                    <p>We may collect personal identification information from Users in a variety of ways in connection with activities, services, features or resources we make available on our Site.. Users may visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.</p>
                    
                    <h4>Non-personal identification information</h4>
                    
                    <p>We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.</p>
                    
                    <h4>Web browser cookies</h4>
                    
                    <!--<p>Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.</p>-->
                    <p>We do not use cookies.</p>
                    
                    <h4>How we protect your information</h4>
                    
                    <p>Our Site is in compliance with PCI vulnerability standards in order to create as secure of an environment as possible for Users.</p>
                    
                    <h4>Sharing your personal information</h4>
                    
                    <p>We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.</p>
                    
                    <h4>Third party websites</h4>
                    
                    <p>Users may find advertising or other content on our Site that link to the sites and services of our partners, suppliers, advertisers, sponsors, licensors and other third parties. We do not control the content or links that appear on these sites and are not responsible for the practices employed by websites linked to or from our Site. In addition, these sites or services, including their content and links, may be constantly changing. These sites and services may have their own privacy policies and customer service policies. Browsing and interaction on any other website, including websites which have a link to our Site, is subject to that website's own terms and policies.</p>
                    
                    <h4>Changes to this privacy policy</h4>
                    
                    <p>XZERO has the discretion to update this privacy policy at any time. When we do, we will post a notification on the main page of our Site, revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.</p>
                    
                    <h4>Your acceptance of these terms</h4>
                    
                    <p>By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.</p>
                    
                    <h4>Contacting us</h4>
                    
                    <p>If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at:<br>
                    <a href="http://xzero.io">XZERO</a><br>
                    <a href="http://xzero.io">http://xzero.io</a><br>
                    Germany, Berlin<br>
                    trapni@gmail.com</p>
                    
                    <span>This document was last updated on September 01, 2013</span>
                        
                </section>
            </aside>
        </section>

<?php $this->partial('shared/footer'); ?>