<?php $this->partial('shared/header'); ?>

        <nav class="font OpenSans warning">
            <aside class="shadow">
                <h6>The website is in beta, we recommend using the latest version of your browser. If you find any bug <a target="_blank" href="https://github.com/xzero/xzero-web/issues">please let us know.</a></h6>
            </aside>
        </nav>
        
        <nav class="header">
            <aside class="shadow">
                <div class="font Ubuntu">
                    <a href="/home" class="active">Home</a>
                    <a href="/docs">Documentation</a>
                    <a href="/plugins">Plugins</a>
                    <a href="http://blog.xzero.io">Blog</a>
                </div>
            </aside>
        </nav>
        
        <section class="welcome">

        
        </section>
<?php $this->partial('shared/footer'); ?>