<?php $this->partial('shared/header'); ?>

        <?php $this->partial('shared/warningBrowser'); ?>
        
        <?php $this->partial('shared/menus'); ?>
        
        <section class="documentation font OpenSans regular">
            <aside class="shadow">
                <div>
                    <strong>Documentation is under construction, please try again later !</strong>
                </div>
            </aside>
        </section>

<?php $this->partial('shared/footer'); ?>