        </section>

        <footer class="webApp">
            <div>
                <aside>
                    <p class="font OpenSans regular">Copyright &copy; 2013 xZero &middot; <a href="/help/privacy">Privacy Policy</a> &middot; <a href="/help/donate">Donate</a> &middot; <a target="_blank" href="https://github.com/xzero/x0">GitHub Repository</a> &middot; <a target="_blank" href="https://github.com/xzero/x0/issues">Issues</a></p>
                </aside>
                
                <span class="credits"><p class="font OpenSans regular">project by <a target="_blank" href="https://github.com/trapni">Christian Parpart</a> <span>&nbsp;</span> design by <a target="_blank" href="https://github.com/pwnsdx">Sabri Haddouche</a></p></span>
            </div>
            <ul>
                <li class="a">
                    <span>
                        <a target="_blank" data-img="https://2.gravatar.com/avatar/3e026293f2500750b8f1e96640af6020?d=https%3A%2F%2Fidenticons.github.com%2Ffbfa1be647c4c60ece5dae662d61f322.png" title="Christian Parpart (trapni)" href="https://github.com/trapni"></a>
                    </span>
                </li>
                <li class="a">
                    <span>
                        <a target="_blank" data-img="https://0.gravatar.com/avatar/4a11809a2134445a8e49cabf87145c9c?d=https%3A%2F%2Fidenticons.github.com%2F9c29e3ddd937b954f6088597082baf7c.png" title="Sabri Haddouche (pwnsdx)" href="https://github.com/pwnsdx"></a>
                    </span>
                </li>
            </ul>
        </footer>
                
    </body>
</html>