        <nav class="header">
            <aside class="shadow">
                <div class="font Ubuntu">
                    <a <?php if($this->view->currentPage != 'home') { ?>data-pajax="true" href="/home"<?php } else { ?>href="javascript: //" class="active"<?php } ?>>Home</a>
                    <a <?php if($this->view->currentPage != 'docs') { ?>data-pajax="true" href="/docs"<?php } else { ?>href="javascript: //" class="active"<?php } ?>>Documentation</a>
                 <a <?php if($this->view->currentPage != 'plugins') { ?>data-pajax="true" href="/plugins"<?php } else { ?>href="javascript: //" class="active"<?php } ?>>Plugins</a>
                    <a href="http://blog.xzero.io" target="_blank">Blog</a>
                </div>
            </aside>
        </nav>