        <nav class="header">
            <aside class="shadow">
                <div class="font Ubuntu">
                    <a href="/home"<?php if($this->view->currentPage == 'home') { ?> class="active"<?php } ?>>Home</a>
                    <a href="/docs"<?php if($this->view->currentPage == 'docs') { ?> class="active"<?php } ?>>Documentation</a>
                    <a href="/plugins"<?php if($this->view->currentPage == 'plugins') { ?> class="active"<?php } ?>>Plugins</a>
                    <a href="http://blog.xzero.io">Blog</a>
                </div>
            </aside>
        </nav>